# ~\AppData\Local\themes\darkMeRio-Slim.toml

[colors]
  tabs = '#395724'
  tabs-active = '#90033a'

  selection-background = '#112725'
  selection-foreground = '#ebdbb2'

  text = "#2c2c2c"
  cursor = '#8fce00'

  background = '#0c0b0c'
  foreground = '#ebdbb2'

# Regular colors
  black  = '#1b1b1b'
  red    = '#cc241d'
  green  = '#98971a'
  yellow = '#d79921'
  blue   = '#458588'
  magenta = '#b16286'
  cyan    = '#689d6a'
  white   = '#a89984'

# Light colors
  light_black   = '#39332d'
  light_red     = '#fb4934'
  light_green   = '#b8bb26'
  light_yellow  = '#fabd2f'
  light_blue    = '#83a598'
  light_magenta = '#d3869b'
  light_cyan    = '#8ec07c'
  light_white   = '#ebdbb2'

# Dim colors
  dim-background = "#202020"
  dim-foreground = "#dbdbdb"

  dim-blue    = "#293e4c"
  dim-cyan    = "#4c8482"
  dim-magenta = "#5e4962"
  dim-green   = "#4e6547"
  dim-white   = "#828282"
  dim-red     = "#74423f"
  dim-black   = "#232323"
  dim-yellow  = "#8b7653"
